console.log("hello there");

age = 'bishnu'
    //datatypes - 8
    //numbere - FP
var population = 324586879;
//let also use
var bigNuber = 3242525642454155155455455445 n;
console.log(1 / 0);
console.log("sdfsf" / 34);
console.log(bigNuber);
//String-Sequence of character
var name = 'bishnu raval';
name = 'bishnu raval';
name = 'bishnu raval';
console.log('my name is ${1+5*6}');

//boolean - true or false
var isAnimal = true;
//undefined
var year;
console.lof(year);

//null
var u = null;

//object
//Symbol
console.log(typeof name);
typeof 0
typeof 45 n
typeof true
typeof 'sdfs'
typeof Symbol('id')
typeof Math
typeof null